version: '2'
services:
   supervisor:
    image: supervisor:3.0
    container_name: supervisor
    working_dir: /app
    ports:
      - '13838:8080/tcp'
    volumes:
       -  ./app/app-0.0.1-SNAPSHOT.jar:/app/app-0.0.1-SNAPSHOT.jar
       -  ./conf/app.conf:/etc/supervisor.conf.d/style.conf
       -  ./logs:/tmp